//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace student_management.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class notificationEntities : DbContext
    {
        public notificationEntities()
            : base("name=notificationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<notification> notifications { get; set; }
        public virtual DbSet<user_noti> user_noti { get; set; }
        public virtual DbSet<VIEW_NOTIFICATION1> VIEW_NOTIFICATION1 { get; set; }
    }
}
