//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace student_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class teacher
    {
        public int id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public Nullable<int> courseid { get; set; }
        public Nullable<int> batchid { get; set; }
        public Nullable<int> registrationid { get; set; }
        public Nullable<int> telno { get; set; }
    
        public virtual branch branch { get; set; }
        public virtual course course { get; set; }
        public virtual registration registration { get; set; }
    }
}
